openapi: 3.0.0
info:
  title: Arithmetic Operations API
  version: 1.0.0
paths:
  /calculate:
    post:
      summary: Perform an arithmetic operation on two numbers.
      tags:
        -  Arithmetic
      operationId: calculate
      parameters:
        - in: header
          name: operation
          schema:
            type: string
            enum: [add, subtract, multiply, divide]
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                number1:
                  type: number
                number2:
                  type: number
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
